version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rails.conf:/etc/nginx/conf.d/rails.conf
      - ./images:/var/www/images # Stream image files with Nginx X-Accel via send_file
    depends_on:
      - rails

  rails:
    build:
      context: rails
    environment:
      - BINDING=0.0.0.0
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/rails
      - ./images:/var/www/images # Stream image files without Nginx X-Accel via send_file
